version: '3.8'
services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medichive
      MYSQL_USER: medi
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    image: harinihimanshi456/medichive:1.4
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: medichive
    depends_on:
      - database
volumes:
  db-data:
    driver: local
    